name: Build Go binaries

on:
    push:
        paths-ignore:
        - 'docs/release.svg'
        - 'README.md'
        - 'CHANGELOG.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Compile
        uses: xxxserxxx/actions/golang-build@v2.0.4
        env:
            SRCPATH: ./cmd/gotop
        with:
          args: darwin/amd64/1 darwin/arm64/1 linux/amd64 linux/386 linux/arm64 linux/arm7 linux/arm6 linux/arm5 windows/amd64/1 windows/386/1 freebsd/amd64/1
