name: Post release triggers

on: 
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF##*/})"
        id: tag_name

      - name: Update Homebrew recipe
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: xxxserxxx/homebrew-gotop
          event-type: my-release
          client-payload: '{"tag": "${{ steps.tag_name.outputs.tag }}"}'

      - name: Update and inform Homebrew
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.homebrew }}
          formula: gotop
          revision: ${{ steps.tag_name.outputs.tag }}

      - name: Update Arch AURs
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: xxxserxxx/gotop-linux
          event-type: my-release
          client-payload: '{"tag": "${{ steps.tag_name.outputs.tag }}"}'

      - name: Trigger extensions build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: xxxserxxx/gotop-builder
          event-type: my-release
          client-payload: '{"tag": "${{ steps.tag_name.outputs.tag }}"}'

      - name: Update current release badge
        shell: bash
        run: sed -i "s/v[0-9]*\.[0-9]*\.[0-9]*/${{steps.tag_name.outputs.tag}}/g" docs/release.svg

      - name: Commit current release badge
        uses: stefanzweifel/git-auto-commit-action@v4.1.0
        with:
            branch: 'master'
            commit_message: Update release badge to version "${{ steps.tag_name.outputs.tag }}"

            # Optional glob pattern of files which should be added to the commit
            file_pattern: docs/release.svg

            # Optional commit user and author settings
            commit_user_name: Badge Updater
            commit_user_email: ser@ser1.net
            commit_author: Badge Updater <ser@ser1.net>
